Ca certificate tests
AnacondaRecipes/ca-certificates-feedstock pull request #9
Opened 2021-12-06 21:18 UTC by abolla22

2021-12-07 15:49 UTC, skupr-anaconda commented on recipe/meta.yaml
>    number: 2
We should bump build number to `3`

2021-12-07 15:52 UTC, skupr-anaconda commented on recipe/meta.yaml
>    home: https://github.com/conda-forge/ca-certificates-feedstock
license should be `MPL-2.0`

2021-12-07 15:52 UTC, skupr-anaconda commented on recipe/meta.yaml
>    home: https://github.com/conda-forge/ca-certificates-feedstock
- No documentation url provided
- No development url provided

2021-12-08 07:19 UTC, skupr-anaconda approved these changes

2021-12-09 17:59 UTC, remkade requested changes
Looks good! I like the `meta.yaml` cleanup.

2021-12-09 17:59 UTC, remkade commented on recipe/run_test.sh
> +}
Can you fix the indentation here?

2021-12-09 20:25 UTC, abolla22 commented on recipe/run_test.sh
> +}
Done

2021-12-10 00:01 UTC, skupr-anaconda approved these changes

2021-12-14 15:21 UTC, abolla22 commented
@remkade  indentation has been fixed can u please review the PR when you get a chance.

2021-12-14 17:18 UTC, remkade approved these changes
Looks good!

2021-12-14 18:08 UTC, merged